version: "3.7"

services:
  web:
    privileged: true
    build: .
    volumes: 
      - .:/app
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: application.py

    ports:
      - '5000:5000'

    command: >
      bash -c "pip install -r requirements.txt
      && gunicorn --worker-class eventlet --bind 0.0.0.0:5000 application:application"
