FROM tiangolo/uwsgi-nginx-flask:python3.6

WORKDIR /app

RUN curl -k -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update
RUN apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1 google-chrome-stable

EXPOSE 8080